# Generated by Django 3.0.5 on 2020-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('sft', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
