# Generated by Django 3.0.5 on 2020-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0002_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
