# Generated by Django 3.0.5 on 2020-04-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0003_auto_20200408_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(default='', upload_to='recommend_system/images')),
                ('image2', models.ImageField(default='', upload_to='recommend_system/images')),
                ('city', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('sft', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
