# Generated by Django 3.0.5 on 2020-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0004_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
        migrations.AddField(
            model_name='home',
            name='image2',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
    ]
