# Generated by Django 3.0.5 on 2020-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0006_home_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='image',
            new_name='landscape1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='image2',
            new_name='landscape2',
        ),
        migrations.AddField(
            model_name='home',
            name='landscape3',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='landscape4',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='landscape5',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='portrait',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
    ]
