# Generated by Django 3.0.5 on 2020-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0008_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
