# Generated by Django 3.0.5 on 2020-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0009_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
