# Generated by Django 3.0.5 on 2020-08-16 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_comment',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
