# Generated by Django 3.0.5 on 2020-08-16 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0013_comment_time_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_comment',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
