# Generated by Django 3.0.5 on 2020-08-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0014_auto_20200816_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_comment',
        ),
    ]
