# Generated by Django 3.0.5 on 2020-08-27 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0018_click_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_broker',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
