# Generated by Django 3.0.5 on 2020-09-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0020_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='search',
            name='post_id',
        ),
    ]
