# Generated by Django 3.0.5 on 2020-09-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0021_auto_20200922_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='username',
            new_name='email',
        ),
    ]
