# Generated by Django 3.0.5 on 2020-09-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0023_remove_search_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='click_item',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='wish_list',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
