# Generated by Django 3.0.5 on 2020-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0024_auto_20200924_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click_item',
            name='datetime',
        ),
    ]
