# Generated by Django 3.0.5 on 2020-09-24 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0025_remove_click_item_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='click_item',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
