# Generated by Django 3.0.5 on 2020-10-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0031_auto_20201006_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommend_system.Home'),
            preserve_default=False,
        ),
    ]
