# Generated by Django 3.0.5 on 2020-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0032_search_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='User email'),
            preserve_default=False,
        ),
    ]
