# Generated by Django 3.0.5 on 2020-10-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0034_auto_20201006_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
