# Generated by Django 3.0.5 on 2020-10-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0038_auto_20201006_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='User email')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_system.Home')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_system.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Search_property',
        ),
    ]
