# Generated by Django 3.0.5 on 2020-10-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0041_auto_20201006_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='post_id',
            new_name='pid',
        ),
    ]
