# Generated by Django 3.0.5 on 2020-10-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0042_auto_20201006_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='recommend_system.Home'),
        ),
    ]
