# Generated by Django 3.0.5 on 2020-10-06 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0043_auto_20201006_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click_item',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='search',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='wish_list',
            name='datetime',
        ),
        migrations.AddField(
            model_name='search',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='search',
            name='post_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recommend_system.Home'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recommend_system.User'),
        ),
    ]
