# Generated by Django 3.0.5 on 2020-10-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0045_auto_20201006_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='post_id',
        ),
    ]
