# Generated by Django 3.0.5 on 2020-10-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0047_remove_search_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='User email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='post_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='recommend_system.Home'),
        ),
    ]
