# Generated by Django 3.0.5 on 2020-10-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0049_auto_20201010_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_system.Home')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_system.User')),
            ],
        ),
    ]
