# Generated by Django 3.0.5 on 2020-11-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0052_auto_20201109_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='user_id',
        ),
    ]
