# Generated by Django 3.0.5 on 2020-12-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0054_auto_20201210_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='city',
        ),
    ]
