# Generated by Django 3.0.5 on 2020-12-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0056_auto_20201211_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='landscape1',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='landscape2',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
        migrations.AddField(
            model_name='home',
            name='landscape3',
            field=models.ImageField(default='', upload_to='recommend_system/images'),
        ),
    ]
