# Generated by Django 3.0.5 on 2020-12-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0057_auto_20201211_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='landscape1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='landscape2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='landscape3',
        ),
    ]
