# Generated by Django 3.0.5 on 2020-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0063_remove_click_item_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='email',
        ),
        migrations.AddField(
            model_name='buy',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='User address'),
            preserve_default=False,
        ),
    ]
