# Generated by Django 3.0.5 on 2020-12-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0064_auto_20201230_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
