# Generated by Django 3.0.5 on 2021-01-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0067_auto_20210103_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='lefteye',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='righteye',
        ),
    ]
