# Generated by Django 3.0.5 on 2021-01-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0068_auto_20210103_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='righteye',
            field=models.IntegerField(default=0),
        ),
    ]
