# Generated by Django 3.0.5 on 2021-01-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0069_buy_righteye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='righteye',
        ),
    ]
