# Generated by Django 3.0.5 on 2021-01-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0070_remove_buy_righteye'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='lefteye',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buy',
            name='righteye',
            field=models.FloatField(default=0.0),
        ),
    ]
