# Generated by Django 3.0.5 on 2021-01-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0072_auto_20210103_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='leye',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='reye',
        ),
    ]
