# Generated by Django 3.0.5 on 2021-01-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0073_auto_20210103_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='leye',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buy',
            name='reye',
            field=models.FloatField(default=0.0),
        ),
    ]
