# Generated by Django 3.0.5 on 2021-01-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_system', '0074_auto_20210103_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='leye',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='reye',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
